kind: ConfigMap
apiVersion: v1
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  __DOMAIN_SUFFIX__.server: |
    __DOMAIN_SUFFIX__:53 {
      errors
      template IN A __DOMAIN_SUFFIX__ {
        match .*.__DOMAIN_SUFFIX__
        answer "{{ .Name }} 60 IN A __GATEWAY_IP__"
      }
      template IN AAAA __DOMAIN_SUFFIX__ {
        match .*.__DOMAIN_SUFFIX__
        rcode NXDOMAIN
      }
      cache 30
      loop
      reload
      loadbalance
    }
