customVolumeMounts:
  x-cx-samples:
    - mountPath: /opt/liferay/osgi/war
      name: liferay-persistent-volume
      subPath: osgi/war
image:
  repository: registry:5000/dxp
  tag: latest
portalProperties: |
  include-and-override=portal-developer.properties
  company.default.virtual.host.mail.domain=main.dxp.localtest.me
  company.default.virtual.host.name=main.dxp.localtest.me
  company.default.web.id=main.dxp.localtest.me
  login.dialog.disabled=true
  passwords.default.policy.change.required=false
  web.server.display.node=true
  web.server.protocol=http
resources:
  limits:
    cpu: 8000m
    memory: 12Gi
  requests:
    cpu: 4000m
    memory: 8Gi
customInitContainers:
  x-liferay-wait-on-services:
    - containerTemplate: |
        -   command:
                -   bash
                -   -c
                -   |
                        trap "echo 'Received signal to terminate.'; exit 0" SIGINT SIGTERM

                        {{- $liferayname := .liferayname }}
                        {{- range $k, $v := .dependencies }}
                            {{- if eq $v.source "statefulset" }}
                                until timeout 2 bash -c '</dev/tcp/{{ $liferayname }}-{{ $k }}/{{ (index $v.statefulset.service.ports 0).port }}' 2>/dev/null
                                do
                                    echo "Waiting for {{ $liferayname }}-{{ $k }}..."

                                    sleep 2
                                done
                            {{- end }}
                        {{- end }}
            image: {{ printf "%s:%s" .image.repository (.image.tag | toString) }}
            imagePullPolicy: {{ .image.pullPolicy }}
            name: liferay-wait-on-services
