configmap:
  data:
    com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration-able.dxp.localtest.me.config: |
      active=B"true"
      maxUsers=I"0"
      mx="able.dxp.localtest.me"
      siteInitializerKey="blank-site-initializer"
      virtualHostname="able.dxp.localtest.me"
      adminScreenName="able"
      adminEmailAddress="able@able.dxp.localtest.me"
      adminFirstName="able"
      adminMiddleName="able"
      adminLastName="able"
      addDefaultAdminUser=B"true"
customVolumeMounts:
   x-saas-bad-configmap:
     - mountPath: /opt/liferay/osgi/configs/com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration~able.dxp.localtest.me.config
       name: liferay-configmap
       subPath: com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration-able.dxp.localtest.me.config
image:
  repository: gamerson/liferayportal-snapshot
  tag: test-lpd-64551-20250904121757
portalProperties: |
  include-and-override=portal-developer.properties
  company.default.virtual.host.mail.domain=main.dxp.localtest.me
  company.default.virtual.host.name=main.dxp.localtest.me
  company.default.web.id=main.dxp.localtest.me
  login.dialog.disabled=true
  passwords.default.policy.change.required=false
  web.server.display.node=true
  web.server.protocol=http
replicaCount: 1
resources:
  limits:
    cpu: 8000m
    memory: 12Gi
  requests:
    cpu: 4000m
    memory: 8Gi
securityContext:
  readOnlyRootFilesystem: false
