customEnv:
  x-cx-direct-deploy-test:
    - name: LIFERAY_JPDA_ENABLED
      value: "true"
customInitContainers:
  x-cx-direct-deploy-test:
    - containerTemplate: |
        - command:
          - bash
          - -c
          - |
            if [ -d /mnt/local/osgi/client-extensions/ ]
            then
              mkdir -p /temp/liferay/deploy
              cp -fv /mnt/local/osgi/client-extensions/*.zip /temp/liferay/deploy
            fi
          image: {{ printf "%s:%s" .image.repository (.image.tag | toString) }}
          imagePullPolicy: {{ .image.pullPolicy }}
          name: cx-direct-deploy-test-init-container
          volumeMounts:
          - mountPath: /temp
            name: liferay-persistent-volume
          - mountPath: /mnt/local
            name: mount-local
customVolumeMounts:
  x-cx-direct-deploy-test:
    - mountPath: /opt/liferay/osgi/war
      name: liferay-persistent-volume
      subPath: osgi/war
image:
  tag: 2025.q1.15-lts
portalProperties: |
  include-and-override=portal-developer.properties
  company.default.virtual.host.mail.domain=main.dxp.localtest.me
  company.default.virtual.host.name=main.dxp.localtest.me
  company.default.web.id=main.dxp.localtest.me
  login.dialog.disabled=true
  web.server.display.node=true
  web.server.protocol=http
resources:
  limits:
    cpu: 6000m
    memory: 12Gi
  requests:
    cpu: 2000m
    memory: 8Gi
