customInitContainers:
  x-cx-message-broker-poc:
    - containerTemplate: |
        - command:
          - bash
          - -c
          - |
            if [ -d /mnt/local/osgi/modules/ ]
            then
              mkdir -p /temp/liferay/deploy
              cp -fv /mnt/local/osgi/modules/*.jar /temp/liferay/deploy
            fi
          image: {{ printf "%s:%s" .image.repository (.image.tag | toString) }}
          imagePullPolicy: {{ .image.pullPolicy }}
          name: cx-message-broker-poc-init-container
          volumeMounts:
          - mountPath: /temp
            name: liferay-persistent-volume
          - mountPath: /mnt/local
            name: mount-local
customVolumeMounts:
  x-cx-message-broker-poc:
    - mountPath: /opt/liferay/osgi/war
      name: liferay-persistent-volume
      subPath: osgi/war
ingress:
  enabled: true
  rules:
  - host: "*.dxp.localtest.me"
    http:
      paths:
      - backend:
          service:
            name: liferay-default
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
portalProperties: |
  include-and-override=portal-developer.properties
  company.default.virtual.host.mail.domain=main.dxp.localtest.me
  company.default.virtual.host.name=main.dxp.localtest.me
  company.default.web.id=main.dxp.localtest.me
  web.server.display.node=true
  web.server.protocol=http
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 6Gi
